server:
  port: 8080
spring:
  application:
    name: university
  # datasource는 DB에 대한 연결 정보를 담고 있다.
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/web
    #url: jdbc:mariadb://172.18.0.2:3306/web
    url: jdbc:mariadb://mariadb:3306/web
    username: beyond
    password: beyond
mybatis:
  type-aliases-package: com.beyond.university.*.model.vo
  mapper-locations:
    - classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: NULL